apiVersion: apps/v1
kind: Deployment
metadata:
  name: fio
  labels:
    test: fio
spec:
  replicas: {{REPLICAS}}
  selector:
    matchLabels:
      test: fio
  template:
    metadata:
      labels:
        test: fio
    spec:
      hostNetwork: true
      nodeSelector:
        fio-dedicated: "true"
      tolerations:
        - key: "fio-dedicated"
          operator: "Equal"
          value: "true"
          effect: "NoExecute"
        - key: "fio-dedicated"
          operator: "Equal"
          value: "true"
          effect: "NoSchedule"
      containers:
        - name: fio
          image: telescope.azurecr.io/perf-eval/fio:3.40
          command: ["sleep infinity"]
          securityContext:
            privileged: true
          volumeMounts:
            - name: data
              mountPath: /mnt/data
      volumes:
        - name: data
          emptyDir: {}
