apiVersion: v1
kind: ConfigMap
metadata:
  name: cl2-override
  namespace: clusterloader2
data:
  override.yaml: |
    NODES: 15000
    PODS_PER_NODE: 180
    BIG_GROUP_SIZE: 8
    MEDIUM_GROUP_SIZE: 8
    SMALL_GROUP_SIZE: 4
    SMALL_STATEFUL_SETS_PER_NAMESPACE: 0
    MEDIUM_STATEFUL_SETS_PER_NAMESPACE: 0
    CL2_SMALL_JOBS_PER_NAMESPACE: 0
    CL2_MEDIUM_JOBS_PER_NAMESPACE: 0
    CL2_BIG_JOBS_PER_NAMESPACE: 0
    CL2_RATE_LIMIT_POD_CREATION: false
    CL2_ENABLE_PVS: false
    CL2_ENABLE_CLUSTER_OOMS_TRACKER: false
    CL2_DEFAULT_QPS: 4000
    CL2_RUN_ON_ARM_NODES: true
---
apiVersion: batch/v1
kind: Job
metadata:
  name: cl2
  namespace: clusterloader2
spec:
  completions: 2
  parallelism: 2
  backoffLimit: 0
  template:
    spec:
      containers:
      - args:
        - '--provider=aks'
        - '--run-from-cluster=true'
        - '--v=2'
        - '--testoverrides=/override/override.yaml'
        - '--testconfig=/testconfig/config.yaml'
        - '--k8s-clients-number=500'
        image: ghcr.io/azure/clusterloader2:v20260220
        name: cl2
        resources:
          requests:
            cpu: '6'
            memory: '24Gi'
        volumeMounts:
        - mountPath: /override
          name: cl2-override
        - mountPath: /testconfig
          name: cl2-testconfig
      nodeSelector:
        agentpool: cl2pool
      restartPolicy: Never
      serviceAccountName: cl2
      tolerations:
      - effect: NoSchedule
        key: cl2pool
        operator: Exists
      volumes:
      - configMap:
          name: cl2-override
        name: cl2-override
      - configMap:
          name: cl2-testconfig
        name: cl2-testconfig
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cl2
  namespace: clusterloader2
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cl2
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cl2
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cl2
subjects:
- kind: ServiceAccount
  name: cl2
  namespace: clusterloader2