apiVersion: v1
kind: Secret
metadata:
  name: clustermesh-additional-scrapes
  namespace: monitoring
type: Opaque
stringData:
  prometheus-additional.yaml: |
    - job_name: kwok-resource
      scheme: http
      scrape_interval: 15s
      scrape_timeout: 10s
      honor_labels: true
      kubernetes_sd_configs:
        - role: node
      relabel_configs:
        - source_labels:
            - __meta_kubernetes_node_annotation_kwok_x_k8s_io_node
          action: keep
          regex: fake
        - source_labels:
            - __meta_kubernetes_node_name
          target_label: node
        - source_labels:
            - __meta_kubernetes_node_name
          target_label: instance
        - source_labels:
            - __meta_kubernetes_node_name
          target_label: __metrics_path__
          replacement: /metrics/nodes/$1/metrics/resource
        - target_label: __address__
          replacement: kwok-controller.kube-system.svc:10247
