#!/bin/bash
set -e

if git diff --cached --name-only | grep -q "^kcl/"; then
    cd kcl/example_pipeline && kcl run pipeline.k -S output -o pipeline.yaml
    cd -
    cd kcl/dovetail_pipeline && kcl run pipeline.k -S output -o pipeline.yaml
    cd -
    git add kcl/example_pipeline/pipeline.yaml
    git add kcl/dovetail_pipeline/pipeline.yaml
fi
