apiVersion: v1
kind: Service
metadata:
  name: wireguard-exporter
  labels:
    app: wireguard-exporter
spec:
  selector:
    app: wireguard-exporter
  ports:
    - name: metrics
      protocol: TCP
      port: 10005
      targetPort: 10005
