apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{.Name}}
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: apiserver-backend-exporter
  namespaceSelector:
    matchNames:
      - monitoring
  podMetricsEndpoints:
    - port: metrics
      path: /metrics
      interval: 15s
      relabelings:
        - replacement: apiserver-backend-exporter
          targetLabel: job
