apiVersion: v1
kind: Service
metadata:
  name: {{.Name}}
  namespace: monitoring
  labels:
    app: apiserver-backend-exporter
spec:
  selector:
    app: apiserver-backend-exporter
  ports:
    - name: metrics
      port: 9100
      targetPort: metrics
