version: 2
updates:

  # Manage dependencies for Terraform
  - package-ecosystem: "terraform"
    directories:
      - "/modules/terraform/*"
    schedule:
      interval: "daily"
    assignees:
      - liyu-ma
    reviewers:
      - liyu-ma
      - vittoriasalim
      - xinWeiWei24
    open-pull-requests-limit: 10
    target-branch: "main"
