apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: psi-reader
  namespace: kube-system
  labels:
    app: psi-reader
spec:
  selector:
    matchLabels:
      app: psi-reader
  template:
    metadata:
      labels:
        app: psi-reader
    spec:
      hostPID: true
      nodeSelector:
        cri-resource-consume: "true"
      tolerations:
      - key: cri-resource-consume
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
      - key: cri-resource-consume
        operator: "Equal"
        value: "true"
        effect: "NoExecute"
      containers:
      - name: psi-reader
        image: alpine:latest
        securityContext:
          privileged: true
        command:
        - /bin/sh
        - -c
        - |
          apk add --no-cache jq
          
          if [ -f /app/config/psi.json ]; then
            rm -f /app/config/psi.json
          fi

          jq -n '{
            "system": {
              "some": {
                "avg10": [],
                "avg60": [],
                "avg300": [],
                "total": []
              },
              "full": {
                "avg10": [],
                "avg60": [],
                "avg300": [],
                "total": []
              },
            },
            "pod": {
              "some": {
                "avg10": [],
                "avg60": [],
                "avg300": [],
                "total": []
              },
              "full": {
                "avg10": [],
                "avg60": [],
                "avg300": [],
                "total": []
              },
            },
            "sys_oom_kill": 0,
            "pod_oom_kill": 0,
            sys_pgscan: 0,
            pod_pgscan: 0
          }' > /app/config/psi.json

          while true; do
            sys_psi=$(cat /sys/fs/cgroup/system.slice/memory.pressure)
            for metric in $sys_psi; do
              if [ $metric == "some" ] || [ $metric == "full" ]; then
                scope=$metric
              else
                key=${metric%%=*}
                value=${metric#*=}
                jq --arg scope "$scope" --arg key "$key" --arg value "$value" '.system[$scope][$key] |= . + [$value]' /app/config/psi.json > psi.json.tmp && mv psi.json.tmp /app/config/psi.json
              fi
            done

            pod_psi=$(cat /sys/fs/cgroup/kubepods.slice/memory.pressure)
            for metric in $pod_psi; do
              if [ $metric == "some" ] || [ $metric == "full" ]; then
                scope=$metric
              else
                key=${metric%%=*}
                value=${metric#*=}
                jq --arg scope "$scope" --arg key "$key" --arg value "$value" '.pod[$scope][$key] |= . + [$value]' /app/config/psi.json > psi.json.tmp && mv psi.json.tmp /app/config/psi.json
              fi
            done

            sys_oom_kill=$(grep oom_kill /sys/fs/cgroup/system.slice/memory.events | awk '{print $2}')
            pod_oom_kill=$(grep oom_kill /sys/fs/cgroup/kubepods.slice/memory.events | awk '{print $2}')
            jq --arg sys_oom_kill "$sys_oom_kill" --arg pod_oom_kill "$pod_oom_kill" '.sys_oom_kill = ($sys_oom_kill | tonumber) | .pod_oom_kill = ($pod_oom_kill | tonumber)' /app/config/psi.json > psi.json.tmp && mv psi.json.tmp /app/config/psi.json

            sys_pgscan=$(grep pgscan /sys/fs/cgroup/system.slice/memory.events | awk '{print $2}')
            pod_pgscan=$(grep pgscan /sys/fs/cgroup/kubepods.slice/memory.events | awk '{print $2}')
            jq --arg sys_pgscan "$sys_pgscan" --arg pod_pgscan "$pod_pgscan" '.sys_pgscan = ($sys_pgscan | tonumber) | .pod_pgscan = ($pod_pgscan | tonumber)' /app/config/psi.json > psi.json.tmp && mv psi.json.tmp /app/config/psi.json
            
            sleep 1
          done
        volumeMounts:
        - name: proc
          mountPath: /proc
          readOnly: true
        - name: systemd
          mountPath: /run/systemd
          readOnly: true
        - name: psi-config
          mountPath: /app/config
      volumes:
      - name: proc
        hostPath:
          path: /proc
          type: Directory
      - name: systemd
        hostPath:
          path: /run/systemd
          type: Directory
      - name: psi-config
        hostPath:
          path: /tmp/telescope-psi-data
          type: DirectoryOrCreate
      restartPolicy: Always
