name: Example Pipeline
pool: AKS-Telescope-Ubuntu-EastUS2
trigger:
- v2
jobs:
- job: deploy_to_azure
  displayName: Deploy to Azure
  steps:
  - task: AzureCLI@2
    inputs:
      azureSubscription: Azure-for-Telescope-internal
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |2

        az account set --subscription "b8ceb4e5-f05b-4562-a9f5-14acb1f24219"
        az config set defaults.location="westus2"
        az account show
    displayName: Login to Azure
  - task: AzureCLI@2
    inputs:
      azureSubscription: Azure-for-Telescope-internal
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |2

        az group create --name "telescope-v2-test" --location "westus2" --subscription "b8ceb4e5-f05b-4562-a9f5-14acb1f24219"
    displayName: Create resource group telescope-v2-test in westus2 (b8ceb4e5-f05b-4562-a9f5-14acb1f24219)
  - task: AzureCLI@2
    inputs:
      azureSubscription: Azure-for-Telescope-internal
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |2

        az cloud update --endpoint-resource-manager https://eastus2euap.management.azure.com/
        az rest \
          --method put \
          --uri "/subscriptions/b8ceb4e5-f05b-4562-a9f5-14acb1f24219/resourceGroups/telescope-v2-test/providers/Microsoft.ContainerService/managedClusters/stg-H2-yaolei?api-version=2026-01-02-preview" \
          --body "
        {
            \"location\": \"westus2\",
            \"identity\": { \"type\": \"SystemAssigned\" },
            \"sku\": {
              \"name\": \"Base\",
              \"tier\": \"Standard\"
            },
            \"tags\": {
              \"exempted_by_qi\": \"36609072\",
              \"SkipAKSCluster\": \"true\",
              \"SkipASMAzSecPackAutoConfig\": \"true\",
              \"SkipLinuxAzSecPack\": \"true\"
            },
            \"properties\": {
              \"controlPlaneScalingProfile\": {\"scalingSize\": \"H2\"},
              \"kubernetesVersion\": \"1.33.0\",
              \"dnsPrefix\": \"stg-H2-yaolei-dns\",
              \"agentPoolProfiles\": [
                {
                  \"name\": \"systempool\",
                  \"mode\": \"System\",
                  \"count\": 3,
                  \"vmSize\": \"Standard_D8S_v4\",
                  \"osType\": \"Linux\"
                }
              ],
            \"networkProfile\": {
               \"networkPlugin\": \"azure\",
               \"networkPluginMode\": \"overlay\",
               \"podCidr\": \"10.64.0.0/10\",
               \"serviceCidr\": \"10.0.0.0/16\",
               \"dnsServiceIP\": \"10.0.0.10\",
               \"outboundType\": \"managedNATGateway\",
               \"natGatewayProfile\": {
                  \"managedOutboundIPProfile\": {
                    \"count\": 10
                  }
                }
              }
            }
          }"
    displayName: Create cluster
  - task: AzureCLI@2
    inputs:
      azureSubscription: Azure-for-Telescope-internal
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |2

        while true; do
          STATE=$(az aks show \
            --name "stg-H2-yaolei" \
            --resource-group "telescope-v2-test" \
            --subscription "b8ceb4e5-f05b-4562-a9f5-14acb1f24219" \
            --query "provisioningState" \
            --output tsv)
          echo "Cluster provisioning state: $STATE"
          if [ "$STATE" = "Succeeded" ]; then
            echo "Cluster is ready."
            break
          elif [ "$STATE" = "Failed" ] || [ "$STATE" = "Canceled" ]; then
            echo "Cluster failed with state: $STATE."
            exit 1
          else
            echo "Provisioning state: $STATE. Retry in 30 seconds"
          fi
          sleep 30
        done
    displayName: Wait for cluster to succeed
  - task: AzureCLI@2
    inputs:
      azureSubscription: Azure-for-Telescope-internal
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |2

        az aks nodepool add \
          --cluster-name "stg-H2-yaolei" \
          --resource-group "telescope-v2-test" \
          --subscription "b8ceb4e5-f05b-4562-a9f5-14acb1f24219" \
          --name "cl2pool" \
          --node-count 1 \
          --node-vm-size "Standard_D8S_v4" \
          --mode User
    displayName: Create node pool cl2pool
  - task: AzureCLI@2
    inputs:
      azureSubscription: Azure-for-Telescope-internal
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |2

        while true; do
          STATE=$(az aks nodepool show \
            --cluster-name "stg-H2-yaolei" \
            --resource-group "telescope-v2-test" \
            --subscription "b8ceb4e5-f05b-4562-a9f5-14acb1f24219" \
            --name "cl2pool" \
            --query "provisioningState" \
            --output tsv)
          echo "Node pool provisioning state: $STATE"
          if [ "$STATE" = "Succeeded" ]; then
            echo "Node pool is ready."
            break
          elif [ "$STATE" = "Failed" ] || [ "$STATE" = "Canceled" ]; then
            echo "Node pool failed with state: $STATE."
            exit 1
          else
            echo "Provisioning state: $STATE. Retry in 30 seconds"
          fi
          sleep 30
        done
    displayName: Wait for node pool cl2pool to succeed
  - task: AzureCLI@2
    inputs:
      azureSubscription: Azure-for-Telescope-internal
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |2

        az aks get-credentials \
          --name "stg-H2-yaolei" \
          --resource-group "telescope-v2-test" \
          --subscription "b8ceb4e5-f05b-4562-a9f5-14acb1f24219" \
          --overwrite-existing
    displayName: Get credentials for stg-H2-yaolei
