apiVersion: apps/v1
kind: Deployment
metadata:
  name: kwok-controller-{{controller_index}}
  namespace: kube-system
  labels:
    app: kwok-controller-{{controller_index}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kwok-controller-{{controller_index}}
  template:
    metadata:
      labels:
        app: kwok-controller-{{controller_index}}
    spec:
      containers:
      - name: kwok-controller
        image: {{controller_image}}
        args:
        - --config=/root/.kwok/kwok.yaml
        - --node-ip=$(POD_IP)
        - --manage-all-nodes=false
        - --manage-nodes-with-label-selector={{node_label_selector}}
        - --manage-nodes-with-annotation-selector=kwok.x-k8s.io/node=fake
        - --server-address=0.0.0.0:10247
        - --node-lease-duration-seconds=60
        env:
        - name: KUBE_API_QPS
          value: "500"
        - name: KUBE_API_BURST
          value: "1000"
        resources:
          limits:
            cpu: "3"
            memory: "20Gi"
          requests:
            cpu: "2"
            memory: "5Gi"
        volumeMounts:
        - name: kwok-config
          mountPath: /root/.kwok/kwok.yaml
          subPath: kwok.yaml
      volumes:
      - name: kwok-config
        configMap:
          name: kwok
      nodeSelector:
        {{node_selector_key}}: "{{node_selector_value}}"
      tolerations:
      - key: {{toleration_key}}
        value: "{{toleration_value}}"
        effect: NoSchedule
      serviceAccountName: kwok-controller
