name: Example Pipeline
pool: AKS-Telescope-Ubuntu-EastUS2
trigger:
- v2
jobs:
- job: deploy_to_azure
  displayName: Deploy to Azure
  steps:
  - task: AzureCLI@2
    inputs:
      azureSubscription: Azure-for-Telescope-internal
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |2

        az account set --subscription "b8ceb4e5-f05b-4562-a9f5-14acb1f24219"
        az config set defaults.location="westus2"
        az account show
    displayName: Login to Azure
  - task: AzureCLI@2
    inputs:
      azureSubscription: Azure-for-Telescope-internal
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |2

        az group create --name "telescope-v2-test" --location "westus2" --subscription "b8ceb4e5-f05b-4562-a9f5-14acb1f24219"
    displayName: Create resource group
  - task: AzureCLI@2
    inputs:
      azureSubscription: Azure-for-Telescope-internal
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |2

        az cloud update --endpoint-resource-manager https://eastus2euap.management.azure.com/
        az rest \
          --method put \
          --uri "/subscriptions/b8ceb4e5-f05b-4562-a9f5-14acb1f24219/resourceGroups/telescope-v2-test/providers/Microsoft.ContainerService/managedClusters/stg-H2-yaolei?api-version=2026-01-02-preview" \
          --body "{
            \"location\": \"westus2\",
            \"identity\": { \"type\": \"SystemAssigned\" },
            \"sku\": {
              \"name\": \"Base\",
              \"tier\": \"Standard\"
            },
            \"tags\": {
              \"exempted_by_qi\": \"36609072\",
              \"SkipAKSCluster\": \"true\",
              \"SkipASMAzSecPackAutoConfig\": \"true\",
              \"SkipLinuxAzSecPack\": \"true\"
            },
            \"properties\": {
              \"controlPlaneScalingProfile\": {\"scalingSize\": \"H2\"},
              \"kubernetesVersion\": \"1.33.0\",
              \"dnsPrefix\": \"stg-H2-yaolei-dns\",
              \"agentPoolProfiles\": [
                {
                  \"name\": \"systempool\",
                  \"mode\": \"System\",
                  \"count\": 3,
                  \"vmSize\": \"Standard_D8S_v4\",
                  \"osType\": \"Linux\"
                }
              ],
            \"networkProfile\": {
               \"networkPlugin\": \"azure\",
               \"networkPluginMode\": \"overlay\",
               \"podCidr\": \"10.64.0.0/10\",
               \"serviceCidr\": \"10.0.0.0/16\",
               \"dnsServiceIP\": \"10.0.0.10\",
               \"outboundType\": \"managedNATGateway\",
               \"natGatewayProfile\": {
                  \"managedOutboundIPProfile\": {
                    \"count\": 10
                  }
                }
              }
            }
          }"
    displayName: Create cluster
