name: Example Pipeline
pool: AKS-Telescope-Ubuntu-EastUS2
trigger:
- v2
jobs:
- job: deploy_to_azure
  displayName: Deploy to Azure
  steps:
  - task: AzureCLI@2
    inputs:
      azureSubscription: Azure-for-Telescope-internal
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        az account set --subscription "b8ceb4e5-f05b-4562-a9f5-14acb1f24219"
        az config set defaults.location="westus2"
        az account show
    displayName: Login to Azure
