apiVersion: acn.azure.com/v1alpha1
kind: ContainerNetworkMetric
metadata:
  name: container-network-metric
spec:
  filters:
    - metric: dns
      includeFilters:
        - name: acns-dns-source
          from:
            labelSelector:
              matchLabels:
                app: acns-client
                k8s.io/namespace: acns-telemetry
          protocol:
            - dns
        - name: acns-dns-destination
          to:
            labelSelector:
              matchLabels:
                app: acns-client
                k8s.io/namespace: acns-telemetry
          protocol:
            - dns
