trigger: none

variables:
  SCENARIO_TYPE: perf-eval
  SCENARIO_NAME: k8s-gpu-cluster-crud

stages:
  - stage: azure_australiaeast
    dependsOn: []
    jobs:
      - template: /jobs/competitive-test.yml
        parameters:
          cloud: azure
          regions:
            - australiaeast
          topology: k8s-crud-gpu
          engine: crud
          matrix:
            statefulset_crud:
              gpu_node_pool: ""
              pool_name: testpool
              vm_size: Standard_D4s_v3
              create_node_count: 0
              scale_node_count: 3
              scale_step_size: 1
              step_time_out: 600
              step_wait_time: 30
              count: 1
              replicas: 10
              manifest_dir: ""
          max_parallel: 1
          credential_type: service_connection
          ssh_key_enabled: false
          timeout_in_minutes: 120
