trigger: none

pool:
  name: 'AKS-Telescope-Airlock'

variables:
  SCENARIO_TYPE: perf-eval

stages:
  - stage: azure_australiaeast_node_pool_crud
    dependsOn: []
    variables:
      SCENARIO_NAME: k8s-gpu-cluster-crud
      AZURE_SERVICE_CONNECTION: Azure (42)
      AZURE_SUBSCRIPTION_ID: c0d4b923-b5ea-4f8f-9b56-5390a9bf2248
    jobs:
      - template: /jobs/competitive-test.yml
        parameters:
          cloud: azure
          regions:
            - australiaeast
          topology: k8s-crud-gpu
          engine: crud
          matrix:
            node_pool_crud_standard:
              VM_SIZE: Standard_D4s_v3
              CREATE_NODE_COUNT: 1
              SCALE_NODE_COUNT: 2
              SCALE_STEP_SIZE: 1
              POOL_NAME: testpool
              STEP_TIME_OUT: 600
              GPU_NODE_POOL: ""
              ENABLE_MANAGED_GPU: "false"
              GPU_INSTANCE_PROFILE: ""
              GPU_MIG_STRATEGY: ""
              STEP_WAIT_TIME: 30
              COUNT: 1
              REPLICAS: 2
              COMPLETIONS: 1
              MANIFEST_DIR: ""
          max_parallel: 1
          credential_type: service_connection
          ssh_key_enabled: false
          timeout_in_minutes: 60

  - stage: azure_canadacentral_machine_crud
    dependsOn: []
    variables:
      SCENARIO_NAME: k8s-cluster-crud-machine
      AZURE_SERVICE_CONNECTION: Azure-for-Telescope-Large-Cluster-Sub
      AZURE_SUBSCRIPTION_ID: 854c9ddb-fe9e-4aea-8d58-99ed88282881
    jobs:
      - template: /jobs/competitive-test.yml
        parameters:
          cloud: azure
          regions:
            - canadacentral
          topology: k8s-cluster-crud-machine
          engine: machine
          matrix:
            machine_crud_small_scale_10:
              VM_SIZE: Standard_D2_v3
              POOL_NAME: smallpool1
              SCALE_MACHINE_COUNT: 10
              MACHINE_WORKERS: 5
              USE_BATCH_API: "false"
              STEP_TIME_OUT: 900
          max_parallel: 1
          credential_type: service_connection
          ssh_key_enabled: false
          timeout_in_minutes: 360
