stages:
- stage: stage_0
  displayName: Stage 0
  jobs:
  - template: pipeline_2.yaml
  - job: job_0_1
    displayName: Job 0-1
    steps:
    - bash: echo s0 j1 step0 xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
      displayName: Step 0-1-0
    - bash: echo s0 j1 step1 xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
      displayName: Step 0-1-1
    - bash: echo s0 j1 step2 xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
      displayName: Step 0-1-2
