apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: myapp-{{NODE_POOL_NAME}}-{{INDEX}}
  labels:
    app: {{LABEL_VALUE}}
spec:
  serviceName: myapp-{{NODE_POOL_NAME}}-{{INDEX}}
  replicas: {{STATEFULSET_REPLICAS}}
  selector:
    matchLabels:
      app: {{LABEL_VALUE}}
  template:
    metadata:
      labels:
        app: {{LABEL_VALUE}}
    spec:
      containers:
        - name: {{LABEL_VALUE}}
          image: mcr.microsoft.com/oss/nginx/nginx:1.21.6
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: myapp-{{NODE_POOL_NAME}}-{{INDEX}}
spec:
  ports:
    - port: 80
      name: myapp
  clusterIP: None
  selector:
    app: {{LABEL_VALUE}}
