apiVersion: cilium.io/v2
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: {{.basename}}
spec:
  endpointSelector:
    matchLabels:
      app: nginx
      actualLabelName: val
  egress:
  - toEndpoints:
    - {}
  ingress:
  - fromEndpoints:
    - {}