apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: {{.basename}}-{{.Index}}
  namespace: {{.namespace}}
spec:
  endpointSelector:
    matchLabels:
      app: nginx
      actualLabelName: val
  egress:
  - toEndpoints:
    - {}