name: deployment-churn

# Config options for test type
{{$SERVICE_TEST := DefaultParam .CL2_SERVICE_TEST true}} # TODO

# Config options for test parameters
{{$nodesPerNamespace := DefaultParam .CL2_NODES_PER_NAMESPACE 100}}
{{$podsPerNode := DefaultParam .CL2_PODS_PER_NODE 50}}
{{$loadTestThroughput := DefaultParam .CL2_LOAD_TEST_THROUGHPUT 100}}
{{$deploymentSize := DefaultParam .CL2_DEPLOYMENT_SIZE 100}}
{{$repeats := DefaultParam .CL2_REPEATS 1}}

{{$latencyPodCpu := DefaultParam .CL2_LATENCY_POD_CPU 10}}
{{$latencyPodMemory := DefaultParam .CL2_LATENCY_POD_MEMORY 50}}
{{$podStartupLatencyThreshold := DefaultParam .CL2_POD_STARTUP_LATENCY_THRESHOLD "15s"}}
{{$namespaces := DivideInt $nodesPerStep $nodesPerNamespace}}
{{$deploymentQPS := DivideFloat $loadTestThroughput $deploymentSize}}
{{$operationTimeout := DefaultParam .CL2_OPERATION_TIMEOUT "15m"}}

{{$totalNodes := MultiplyInt $nodesPerStep $steps}}
{{$totalPods := MultiplyInt $nodesPerStep $steps $podsPerNode}}
{{$podsPerNamespace := DivideInt $totalPods $namespaces}}
{{$deploymentsPerNamespace := DivideInt $podsPerNamespace (MultiplyInt $deploymentSize $steps)}}

{{$RATE_LIMIT_POD_CREATION := DefaultParam .CL2_RATE_LIMIT_POD_CREATION true}}
{{$ADDITIONAL_MEASUREMENT_MODULES := DefaultParam .CL2_ADDITIONAL_MEASUREMENT_MODULES nil}}

# Service test
{{$BIG_GROUP_SIZE := DefaultParam .BIG_GROUP_SIZE 4000}}
{{$SMALL_GROUP_SIZE := DefaultParam .SMALL_GROUP_SIZE 20}}
{{$bigDeploymentsPerNamespace := DefaultParam .bigDeploymentsPerNamespace 1}}
{{$smallDeploymentPods := SubtractInt $podsPerNamespace (MultiplyInt .bigDeploymentsPerNamespace $BIG_GROUP_SIZE)}}
{{$smallDeploymentsPerNamespace := DivideInt $smallDeploymentPods $SMALL_GROUP_SIZE}}

namespace:
  number: {{$namespaces}}
  prefix: slo
  deleteStaleNamespaces: true
  deleteAutomanagedNamespaces: true
  enableExistingNamespaces: false

tuningSets:
  - name: DeploymentCreateQps
    qpsLoad:
      qps: {{$deploymentQPS}}
  - name: DeploymentDeleteQps
    qpsLoad:
      qps: {{$deploymentQPS}}

steps:
  - name: Log - totalNodes={{$totalNodes}}, namespaces={{$namespaces}}, nodesPerNamespace={{$nodesPerNamespace}}, podsPerNode={{$podsPerNode}}, totalPods={{$totalPods}}, podsPerNamespace={{$podsPerNamespace}}, deploymentsPerNamespace={{$deploymentsPerNamespace}}, deploymentSize={{$deploymentSize}}, deploymentQPS={{$deploymentQPS}}
    measurements:
    - Identifier: Dummy
      Method: Sleep
      Params:
        action: start
        duration: 1ms

  - module:
      path: /modules/measurements.yaml
      params:
        action: start

# TODO: If AKS+Cilium, enable additional Cilium measurements.

{{range $i := Loop $repeats}}
{{if $SERVICE_TEST}}
  - module:
      path: /modules/services.yaml
      params:
        actionName: "Creating"
        namespaces: {{$namespaces}}
        smallServicesPerNamespace: {{$smallDeploymentsPerNamespace}}
        bigServicesPerNamespace: {{$bigDeploymentsPerNamespace}}
{{end}}

  - module:
      path: /modules/reconcile-objects.yaml
      params:
        actionName: "create"
        namespaces: {{$namespaces}}
        tuningSet: DeploymentCreateQps
        operationTimeout: 15m
        bigDeploymentSize: {{$BIG_GROUP_SIZE}}
        bigDeploymentsPerNamespace: {{$bigDeploymentsPerNamespace}}
        smallDeploymentSize: {{$SMALL_GROUP_SIZE}}
        smallDeploymentsPerNamespace: {{$smallDeploymentsPerNamespace}}
        CpuRequest: {{$latencyPodCpu}}m
        MemoryRequest: {{$latencyPodMemory}}M
        Group: deployment-churn

  - module:
      path: /modules/reconcile-objects.yaml
      params:
        actionName: "delete"
        namespaces: {{$namespaces}}
        tuningSet: DeploymentDeleteQps
        operationTimeout: 15m
        bigDeploymentSize: {{$BIG_GROUP_SIZE}}
        bigDeploymentsPerNamespace: 0
        smallDeploymentSize: {{$SMALL_GROUP_SIZE}}
        smallDeploymentsPerNamespace: 0

  - module:
      path: /modules/services.yaml
      params:
        actionName: "Deleting"
        namespaces: {{$namespaces}}
        smallServicesPerNamespace: 0
        bigServicesPerNamespace: 0

{{end}}

  - module:
    path: /modules/measurements.yaml
    params:
      action: gather
