"""v1 reference outputs generated by fixtures/generate_v1_golden.py."""
import json
import os

GOLDEN_FILE = os.path.join(os.path.dirname(__file__), "fixtures", "v1_golden.json")

with open(GOLDEN_FILE, encoding="utf-8") as golden_file:
    V1_GOLDEN = json.load(golden_file)
