parameters:
  cloud: ""

steps:
- script: |
    set -eo pipefail

    # Create Node Pool
    PYTHONPATH=$PYTHONPATH:$(pwd) python3 "$PYTHON_SCRIPT_FILE" create \
      --cloud "$CLOUD" \
      --run-id "$RUN_ID" \
      --result-dir "$RESULT_DIR" \
      --node-pool-name "$POOL_NAME" \
      --vm-size "$VM_SIZE" \
      --node-count "$CREATE_NODE_COUNT" \
      --step-timeout "$STEP_TIME_OUT" \
      ${GPU_NODE_POOL:+--gpu-node-pool} \
      $([[ "${ENABLE_MANAGED_GPU,,}" == "true" ]] && echo "--enable-managed-gpu" || true) \
      $([[ "${GPU_INSTANCE_PROFILE}" =~ ^MIG ]] && echo "--gpu-instance-profile ${GPU_INSTANCE_PROFILE}" || true) \
      $([[ "${GPU_MIG_STRATEGY}" =~ ^(mixed|single)$ ]] && echo "--gpu-mig-strategy ${GPU_MIG_STRATEGY}" || true) \
      --capacity-type "${CAPACITY_TYPE:-ON_DEMAND}"

    # Scale Up Node Pool
    PYTHONPATH=$PYTHONPATH:$(pwd) python3 "$PYTHON_SCRIPT_FILE" scale \
      --cloud "$CLOUD" \
      --run-id "$RUN_ID" \
      --result-dir "$RESULT_DIR" \
      --node-pool-name "$POOL_NAME" \
      --target-count "$SCALE_NODE_COUNT" \
      --scale-step-size "$SCALE_STEP_SIZE" \
      --step-wait-time "$STEP_WAIT_TIME" \
      --step-timeout "$STEP_TIME_OUT" \
      ${GPU_NODE_POOL:+--gpu-node-pool} \
      $([[ "${ENABLE_MANAGED_GPU,,}" == "true" ]] && echo "--enable-managed-gpu" || true) \
      $([[ "${GPU_INSTANCE_PROFILE}" =~ ^MIG ]] && echo "--gpu-instance-profile ${GPU_INSTANCE_PROFILE}" || true) \
      $([[ "${GPU_MIG_STRATEGY}" =~ ^(mixed|single)$ ]] && echo "--gpu-mig-strategy ${GPU_MIG_STRATEGY}" || true)

  displayName: 'Execute K8s Create & Scale Up Operations for ${{ parameters.cloud }}'
  workingDirectory: modules/python
  env:
    PYTHON_SCRIPT_FILE: $(Pipeline.Workspace)/s/modules/python/crud/main.py
    VM_SIZE: $(VM_SIZE)
    CREATE_NODE_COUNT: $(CREATE_NODE_COUNT)
    SCALE_NODE_COUNT: $(SCALE_NODE_COUNT)
    SCALE_STEP_SIZE: $(SCALE_STEP_SIZE)
    POOL_NAME: $(POOL_NAME)
    CLOUD: ${{ parameters.cloud }}
    STEP_TIME_OUT: $(STEP_TIME_OUT)
    RESULT_DIR: $(System.DefaultWorkingDirectory)/$(RUN_ID)
    GPU_NODE_POOL: $(GPU_NODE_POOL)
    ENABLE_MANAGED_GPU: $(ENABLE_MANAGED_GPU)
    GPU_INSTANCE_PROFILE: $(GPU_INSTANCE_PROFILE)
    GPU_MIG_STRATEGY: $(GPU_MIG_STRATEGY)
    STEP_WAIT_TIME: $(STEP_WAIT_TIME)
    ${{ if eq(parameters.cloud, 'aws') }}:
      CAPACITY_TYPE: $(CAPACITY_TYPE)

- ${{ if eq(parameters.cloud, 'azure') }}:
  - script: |
      set -eo pipefail

      # Deploy Workloads
      PYTHONPATH=$PYTHONPATH:$(pwd) python3 "$PYTHON_SCRIPT_FILE" deployment \
        --cloud "$CLOUD" \
        --run-id "$RUN_ID" \
        --result-dir "$RESULT_DIR" \
        --node-pool-name "$POOL_NAME" \
        --count "$COUNT" \
        --replicas "$REPLICAS" \
        ${MANIFEST_DIR:+--manifest-dir "$MANIFEST_DIR"} \
        --step-timeout "$STEP_TIME_OUT" \
        ${GPU_NODE_POOL:+--gpu-node-pool} \
        $([[ "${ENABLE_MANAGED_GPU,,}" == "true" ]] && echo "--enable-managed-gpu" || true)
    displayName: 'Execute K8s Workload operations for ${{ parameters.cloud }}'
    workingDirectory: modules/python
    env:
      PYTHON_SCRIPT_FILE: $(Pipeline.Workspace)/s/modules/python/crud/main.py
      POOL_NAME: $(POOL_NAME)
      CLOUD: ${{ parameters.cloud }}
      STEP_TIME_OUT: $(STEP_TIME_OUT)
      RESULT_DIR: $(System.DefaultWorkingDirectory)/$(RUN_ID)
      GPU_NODE_POOL: $(GPU_NODE_POOL)
      ENABLE_MANAGED_GPU: $(ENABLE_MANAGED_GPU)
      COUNT: $(COUNT)
      REPLICAS: $(REPLICAS)
      MANIFEST_DIR: $(MANIFEST_DIR)

  - script: |
      set -eo pipefail

      # Deploy StatefulSets
      PYTHONPATH=$PYTHONPATH:$(pwd) python3 "$PYTHON_SCRIPT_FILE" statefulset \
        --cloud "$CLOUD" \
        --run-id "$RUN_ID" \
        --result-dir "$RESULT_DIR" \
        --node-pool-name "$POOL_NAME" \
        --count "$COUNT" \
        --replicas "$REPLICAS" \
        ${MANIFEST_DIR:+--manifest-dir "$MANIFEST_DIR"} \
        --step-timeout "$STEP_TIME_OUT" \
        ${GPU_NODE_POOL:+--gpu-node-pool} \
        $([[ "${ENABLE_MANAGED_GPU,,}" == "true" ]] && echo "--enable-managed-gpu" || true)
    displayName: 'Execute K8s StatefulSet operations for ${{ parameters.cloud }}'
    workingDirectory: modules/python
    env:
      PYTHON_SCRIPT_FILE: $(Pipeline.Workspace)/s/modules/python/crud/main.py
      POOL_NAME: $(POOL_NAME)
      CLOUD: ${{ parameters.cloud }}
      STEP_TIME_OUT: $(STEP_TIME_OUT)
      RESULT_DIR: $(System.DefaultWorkingDirectory)/$(RUN_ID)
      GPU_NODE_POOL: $(GPU_NODE_POOL)
      ENABLE_MANAGED_GPU: $(ENABLE_MANAGED_GPU)
      COUNT: $(COUNT)
      REPLICAS: $(REPLICAS)
      MANIFEST_DIR: $(MANIFEST_DIR)

  - script: |
      set -eo pipefail

      # Deploy Jobs
      PYTHONPATH=$PYTHONPATH:$(pwd) python3 "$PYTHON_SCRIPT_FILE" job \
        --cloud "$CLOUD" \
        --run-id "$RUN_ID" \
        --result-dir "$RESULT_DIR" \
        --node-pool-name "$POOL_NAME" \
        --count "$COUNT" \
        --completions "$COMPLETIONS" \
        ${MANIFEST_DIR:+--manifest-dir "$MANIFEST_DIR"} \
        --step-timeout "$STEP_TIME_OUT" \
        ${GPU_NODE_POOL:+--gpu-node-pool} \
        $([[ "${ENABLE_MANAGED_GPU,,}" == "true" ]] && echo "--enable-managed-gpu" || true)
    displayName: 'Execute K8s Job operations for ${{ parameters.cloud }}'
    workingDirectory: modules/python
    env:
      PYTHON_SCRIPT_FILE: $(Pipeline.Workspace)/s/modules/python/crud/main.py
      POOL_NAME: $(POOL_NAME)
      CLOUD: ${{ parameters.cloud }}
      STEP_TIME_OUT: $(STEP_TIME_OUT)
      RESULT_DIR: $(System.DefaultWorkingDirectory)/$(RUN_ID)
      GPU_NODE_POOL: $(GPU_NODE_POOL)
      ENABLE_MANAGED_GPU: $(ENABLE_MANAGED_GPU)
      COUNT: $(COUNT)
      COMPLETIONS: $(COMPLETIONS)
      MANIFEST_DIR: $(MANIFEST_DIR)

- script: |
    set -eo pipefail

    # Scale Down Node Pool
    PYTHONPATH=$PYTHONPATH:$(pwd) python3 "$PYTHON_SCRIPT_FILE" scale \
      --cloud "$CLOUD" \
      --run-id "$RUN_ID" \
      --result-dir "$RESULT_DIR" \
      --node-pool-name "$POOL_NAME" \
      --target-count "$CREATE_NODE_COUNT" \
      --scale-step-size "$SCALE_STEP_SIZE" \
      --step-wait-time "$STEP_WAIT_TIME" \
      --step-timeout "$STEP_TIME_OUT" \
      ${GPU_NODE_POOL:+--gpu-node-pool} \
      $([[ "${ENABLE_MANAGED_GPU,,}" == "true" ]] && echo "--enable-managed-gpu" || true) \
      $([[ "${GPU_INSTANCE_PROFILE}" =~ ^MIG ]] && echo "--gpu-instance-profile ${GPU_INSTANCE_PROFILE}" || true) \
      $([[ "${GPU_MIG_STRATEGY}" =~ ^(mixed|single)$ ]] && echo "--gpu-mig-strategy ${GPU_MIG_STRATEGY}" || true)

    # Delete Node Pool
    PYTHONPATH=$PYTHONPATH:$(pwd) python3 "$PYTHON_SCRIPT_FILE" delete \
      --cloud "$CLOUD" \
      --run-id "$RUN_ID" \
      --result-dir "$RESULT_DIR" \
      --node-pool-name "$POOL_NAME" \
      --step-timeout "$STEP_TIME_OUT"
  displayName: 'Execute K8s Scale Down & Delete Operations for ${{ parameters.cloud }}'
  condition: always()
  workingDirectory: modules/python
  env:
    PYTHON_SCRIPT_FILE: $(Pipeline.Workspace)/s/modules/python/crud/main.py
    VM_SIZE: $(VM_SIZE)
    CREATE_NODE_COUNT: $(CREATE_NODE_COUNT)
    SCALE_NODE_COUNT: $(SCALE_NODE_COUNT)
    SCALE_STEP_SIZE: $(SCALE_STEP_SIZE)
    POOL_NAME: $(POOL_NAME)
    CLOUD: ${{ parameters.cloud }}
    STEP_TIME_OUT: $(STEP_TIME_OUT)
    RESULT_DIR: $(System.DefaultWorkingDirectory)/$(RUN_ID)
    GPU_NODE_POOL: $(GPU_NODE_POOL)
    ENABLE_MANAGED_GPU: $(ENABLE_MANAGED_GPU)
    GPU_INSTANCE_PROFILE: $(GPU_INSTANCE_PROFILE)
    GPU_MIG_STRATEGY: $(GPU_MIG_STRATEGY)
    STEP_WAIT_TIME: $(STEP_WAIT_TIME)
    ${{ if eq(parameters.cloud, 'aws') }}:
      CAPACITY_TYPE: $(CAPACITY_TYPE)
