parameters:
  - name: cloud
    type: string
  - name: result_dir
    type: string
  - name: vm_size
    type: string
  - name: pool_name
    type: string
  - name: scale_machine_count
    type: string  # numeric matrix values resolve at runtime via $(VAR)
  - name: machine_workers
    type: string
  - name: use_batch_api
    type: string  # 'true'|'false' as ADO doesn't have boolean type for matrix
  - name: step_time_out
    type: string
    default: "600"

steps:
  - script: |
      set -eo pipefail
      PYTHONPATH=$PYTHONPATH:$(pwd) python3 "$PYTHON_SCRIPT_FILE" create-machine \
        --cloud "${{ parameters.cloud }}" \
        --run-id "$RUN_ID" \
        --node-pool-name "${{ parameters.pool_name }}" \
        --vm-size "${{ parameters.vm_size }}" \
        --step-timeout "${{ parameters.step_time_out }}" \
        --result-dir "${{ parameters.result_dir }}"
      USE_BATCH_FLAG=""
      if [[ "${{ parameters.use_batch_api }}" == "true" ]]; then
        USE_BATCH_FLAG="--use-batch-api"
      fi
      # shellcheck disable=SC2086
      PYTHONPATH=$PYTHONPATH:$(pwd) python3 "$PYTHON_SCRIPT_FILE" scale-machine \
        --cloud "${{ parameters.cloud }}" \
        --run-id "$RUN_ID" \
        --node-pool-name "${{ parameters.pool_name }}" \
        --vm-size "${{ parameters.vm_size }}" \
        --scale-machine-count "${{ parameters.scale_machine_count }}" \
        --machine-workers "${{ parameters.machine_workers }}" \
        $USE_BATCH_FLAG \
        --step-timeout "${{ parameters.step_time_out }}" \
        --readiness-wait-timeout "${{ parameters.step_time_out }}" \
        --result-dir "${{ parameters.result_dir }}"
    workingDirectory: modules/python
    displayName: "Execute Machine API CRUD"
    env:
      PYTHON_SCRIPT_FILE: $(Pipeline.Workspace)/s/modules/python/crud/main.py
      RUN_ID: $(RUN_ID)
