trigger: none
schedules:
  - cron: "0 */2 * * *"
    displayName: "Every 2 Hour"
    branches:
      include:
        - alyssa/kube-reserved
    always: true

variables:
  SCENARIO_TYPE: perf-eval
  SCENARIO_NAME: kube-reserved
  SCENARIO_VERSION: alyssa/kube-reserved

stages:
  - stage: azure_westeurope
    dependsOn: []
    jobs:
      - template: /jobs/competitive-test.yml
        parameters:
          cloud: azure
          regions:
            - westeurope
          engine: clusterloader2
          engine_input:
            image: "ghcr.io/azure/clusterloader2:v20241016"
          topology: kube-reserved
          matrix:
            n3-p750:
              node_count: 3
              max_pods: 250
              repeats: 1
              operation_timeout: 5m
          max_parallel: 1
          timeout_in_minutes: 120
          credential_type: service_connection
          ssh_key_enabled: false
  - stage: aws_westeurope
    dependsOn: []
    jobs:
      - template: /jobs/competitive-test.yml
        parameters:
          cloud: aws
          regions:
            - us-west-1
          engine: clusterloader2
          engine_input:
            image: "ghcr.io/azure/clusterloader2:v20241016"
          topology: kube-reserved
          matrix:
            n3-p750:
              node_count: 3
              max_pods: 250
              repeats: 1
              operation_timeout: 5m
          max_parallel: 1
          timeout_in_minutes: 120
          credential_type: service_connection
          ssh_key_enabled: false
