trigger: none
pr: none

variables:
  SCENARIO_TYPE: perf-eval
  SCENARIO_NAME: acl-resource-consume
  ACL_IMAGE_SUBSCRIPTION_ID: b3e01d89-bd55-414f-bbb4-cdfeb2628caa
  ACL_IMAGE_RESOURCE_GROUP: ACL-IMAGES
  ACL_IMAGE_GALLERY: acl
  ACL_IMAGE_NAME: acl-aks
  ACL_IMAGE_VERSION: 1.1775601122.6691
  AKS_CLI_CUSTOM_HEADERS: >-
    AKSHTTPCustomFeatures=Microsoft.ContainerService/UseCustomizedOSImage,
    OSImageSubscriptionID=$(ACL_IMAGE_SUBSCRIPTION_ID),
    OSImageResourceGroup=$(ACL_IMAGE_RESOURCE_GROUP),
    OSImageGallery=$(ACL_IMAGE_GALLERY),
    OSImageName=$(ACL_IMAGE_NAME),
    OSImageVersion=$(ACL_IMAGE_VERSION),
    OSSKU=AzureContainerLinux,
    OSDistro=CustomizedImageLinuxGuard

stages:
  - stage: acl_resource_consume
    displayName: ACL CRI resource consume (westus2)
    dependsOn: []
    jobs:
      - template: /jobs/competitive-test.yml
        parameters:
          cloud: azure
          regions:
            - westus2
          engine: clusterloader2
          engine_input:
            image: "ghcr.io/azure/clusterloader2:v20250513"
          topology: cri-resource-consume
          matrix:
            n10-p300-memory:
              node_count: 10
              max_pods: 30
              repeats: 1
              operation_timeout: 3m
              load_type: memory
              scrape_kubelets: True
              os_type: linux
          max_parallel: 1
          timeout_in_minutes: 120
          credential_type: service_connection
          ssh_key_enabled: false
