apiVersion: v1
kind: ConfigMap
metadata:
  name: ama-metrics-prometheus-config
  namespace: kube-system
data:
  prometheus-config: |-
    global:
      scrape_interval: 15s
      scrape_timeout: 10s
    scrape_configs:
      - job_name: cilium-hubble-full
        honor_labels: true
        kubernetes_sd_configs:
          - role: pod
            namespaces:
              names: [kube-system]
        relabel_configs:
          - source_labels:
              - __meta_kubernetes_pod_label_k8s_app
            action: keep
            regex: cilium
          - source_labels:
              - __meta_kubernetes_pod_phase
            action: keep
            regex: Running
          - source_labels:
              - __meta_kubernetes_pod_ip
            target_label: __address__
            replacement: $1:9965
          - source_labels:
              - __meta_kubernetes_pod_node_name
            target_label: node
      - job_name: clustermesh-apiserver-full
        honor_labels: true
        kubernetes_sd_configs:
          - role: pod
            namespaces:
              names: [kube-system]
        relabel_configs:
          - source_labels:
              - __meta_kubernetes_pod_label_k8s_app
            action: keep
            regex: clustermesh-apiserver
          - source_labels:
              - __meta_kubernetes_pod_ip
            target_label: __address__
            replacement: $1:9963
      - job_name: kvstoremesh-full
        honor_labels: true
        kubernetes_sd_configs:
          - role: pod
            namespaces:
              names: [kube-system]
        relabel_configs:
          - source_labels:
              - __meta_kubernetes_pod_label_k8s_app
            action: keep
            regex: clustermesh-apiserver|kvstoremesh
          - source_labels:
              - __meta_kubernetes_pod_ip
            target_label: __address__
            replacement: $1:9964
      - job_name: kwok-resource
        honor_labels: true
        kubernetes_sd_configs:
          - role: node
        relabel_configs:
          - source_labels:
              - __meta_kubernetes_node_annotation_kwok_x_k8s_io_node
            action: keep
            regex: fake
          - source_labels:
              - __meta_kubernetes_node_name
            target_label: node
          - source_labels:
              - __meta_kubernetes_node_name
            target_label: instance
          - source_labels:
              - __meta_kubernetes_node_name
            target_label: __metrics_path__
            replacement: /metrics/nodes/$1/metrics/resource
          - target_label: __address__
            replacement: kwok-controller.kube-system.svc:10247
