apiVersion: azmonitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: apiserver-backend-exporter
  namespace: kube-system
spec:
  labelLimit: 63
  labelNameLengthLimit: 511
  labelValueLengthLimit: 1023
  selector:
    matchLabels:
      app: apiserver-backend-exporter
  namespaceSelector:
    matchNames:
      - monitoring
  podMetricsEndpoints:
    - port: metrics
      interval: 15s
      path: /metrics
      relabelings:
        - replacement: apiserver-backend-exporter
          targetLabel: job
