apiVersion: azmonitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: mock-cilium-agent-full
  namespace: mock-clustermesh
spec:
  labelLimit: 63
  labelNameLengthLimit: 511
  labelValueLengthLimit: 1023
  selector:
    matchLabels:
      app: mock-cilium-agent
  namespaceSelector:
    matchNames:
      - mock-clustermesh
  podMetricsEndpoints:
    - port: prometheus
      interval: 15s
      path: /metrics
      honorLabels: true
      relabelings:
        - replacement: mock-cilium-agent-full
          targetLabel: job
        - sourceLabels:
            - __meta_kubernetes_pod_label_mock_clustermesh_serves_node
          targetLabel: node
